### PR TITLE
Changed URL for API reference to be shorter

### PR DESCRIPTION
**Pull request by philipstarkey**
Shortened the URL for the API reference from `../api-reference/...` to `.../api/...`

Will update the others to follow this if people agree.

(Also mainly I did this so we could see what the RTD PR integration looked like!)

### CODE REVIEW

**Comment by philipstarkey** [comment]
Cool! You can view the build result [here](https://labscriptsuite--57.org.readthedocs.build/projects/labscript-utils/en/57/) (or by clicking "show all checks" above and then "details" on the RTD entry.

This negates the need to setup our own RTD projects for our forks (although I may keep mine anyway so I can see the result before making a PR).

**Comment by rpanderson** [comment]
`labscript_suite_doc_version` is stable in the preview build. Is this intentional/expected?

**Comment by philipstarkey** [comment]
> `labscript_suite_doc_version` is stable in the preview build. Is this intentional/expected?

No...I'll debug

**Comment by philipstarkey** [comment]
Ok, hopefully this will fix it. I had to distinguish between prior tagged versions (with a RTD_VERSION like 3.0.0) and PR versions (which have a RTD_VERSION like 57 - the PR number)

**Comment by philipstarkey** [comment]
Noticed a deprecated warning (for the stylesheet) while looking through the build logs so I fixed that too while I was at it. We can copy/paste the updated general config (lines 35 onwards) into the other projects to fix both issues.

**Pull request merged**
