### PR TITLE
Example labscript and analysis scripts for IMAQdxCamera and RemoteBLACS

### PR DESCRIPTION
**Pull request by rpanderson**
This example builds upon [testing/test.py](https://github.com/labscript-suite/labscript-devices/blob/master/labscript_devices/IMAQdxCamera/testing/test.py) in [`labscript_devices.IMAQdxCamera`](https://github.com/labscript-suite/labscript-devices/tree/master/labscript_devices/IMAQdxCamera), and illustrates basic usage of the `IMAQdxCamera` labscript device and `RemoteBLACS`. Included are a connection table and labscript experiment script (in userlib/labscriptlib/example_apparatus), and a lyse analysis script (in userlib/analysislib/example_apparatus).

Usage of the following methods of `lyse.Run` are demonstrated: `get_globals()`, `get_images()`, `save_result()`, as well as `lyse.spinning_top`, `lyse.path`, and `lyse.data()`.

## runmanager settings

The labscript experiment script example_IMAQdx_remote.py is loaded into runmanager:

image

## blacs display
The IMAQdxCamera in `mock` mode displays the synthetic data after each shot:

image

## `RemoteBLACS` server
The `RemoteBLACS` server (started using `python -m labscript_utils.remote`) shown in a separate terminal:

image

## lyse singleshot routines dialog
The single-shot analysis routine example_IMAQdx_remote.py is loaded into lyse:

image

## Example analysis output 

A 1D plot generated from lineouts of the synthetic image data is displayed:
image
 
The plot updates automatically when new shots are added to the lyse analysis queue by blacs.

### CODE REVIEW

**Comment by rpanderson** [comment]
_Note:_ The connection table is not compatible with that in #54, so to use this one would need to change the `connection_table_py` in their labconfig, and recompile the connection table.

```ini
[paths]
connection_table_py = %(labscriptlib)s\connection_table_IMAQdx_remote.py
```

I'm open to modifying the example connection table in #54 to be a superset of example devices, but I don't think this will scale to all examples, and it detracts from the minimalism of the example.

**Comment by chrisjbillington** [comment]
Happy to merge, russ?

**Comment by rpanderson** [comment]
Yes, subject to your endorsement of the choice to **not** make the base example connection_table.py (#54) be a superset which includes this example's connection table.

**Comment by chrisjbillington** [comment]
Yeah, individual simple examples rather than a kitchen-sink approach seems sensible to me.

Thanks for this!

**Pull request merged**
